[tox]
skipsdist = true
envlist = py38

[flake8]
# IGNORE THESE ERRORS.
#   D: flake8-docstrings/pydocstyle - http://pep257.readthedocs.io/en/latest/error_codes.html
#   H: hacking/openstack python style guide
#   P: flake8-string-format
#   S: flake8-pep3101 (% vs str.format())
#   W: flake8 whitespace
# D100: Missing docstring in public module
# D104: Missing docstring in public package
# D105: Missing docstring in magic method
# D200: One-line docstring should fit on one line with quotes
# D204: 1 blank line required after class docstring
# D205: 1 blank line required between summary line and description
# D301: Use r""" if any backslashes in a docstring
# D302: Use u""" for Unicode docstrings
# D400: First line should end with a period
# D401: First line should be in imperative mood
# D402: First line should not be the function's "signature"
# D403: First word of the first line should be properly capitalized
# D404: First word of the docstring should not be `This`
# E741 ambiguous variable name
# H101: Use TODO(NAME)
# H301: one import per line
# H306: imports not in alphabetical order (time, os)
# H401: docstring should not start with a space
# H404: multi line docstring should start without a leading new line
# H405: multi line docstring summary not separated with an empty line
# N804: first argument of a classmethod should be named 'cls'
# N805: first argument of a method should be named 'self'
# P102: docstring does contain unindexed parameters
# P302: format call provides unused keyword (e.g. 'exc_info')
# S001: found module formatter
# W503: Line break before binary operator
# W504: line break after binary operator
ignore = D100,D104,D105,D200,D204,D205,D301,D302,D400,D401,D402,D403,D404,E741,H101,H301,H306,H401,H404,H405,N804,N805,P102,P302,S001,W503,W504
inline_quotes = double
max_line_length = 240

[pycodestyle]
max-line-length = 240
show-source = true

# exclude files or directories which match these comma separated patterns
# (default: .svn,CVS,.bzr,.hg,.git,__pycache__,.tox)
exclude = .svn,CVS,.bzr,.hg,.git,__pycache__,.tox,node_modules,scripts/manage_keys/contrib

# skip errors and warnings (e.g. E4,W)
# (default: E121,E123,E126,E226,E24,E704)
#
# E203 whitespace before ':' -- NOT PEP8 compliant, fights black: https://github.com/psf/black/blob/master/docs/the_black_code_style.md#slices
# E402 module level import not at top of file
# E722 do not use bare except, specify exception instead
# E741 do not use variables named 'l', 'O', or 'I'
# W504 line break after binary operator
# W605 invalid escape sequence 'x'
ignore = E128,E121,E123,E126,E226,E24,E203,E402,E704,E722,E741,W503,W504,W605

[testenv]
setenv =
    PYTHONHASHSEED=0
deps =
    -rdev-requirements.txt
commands =
    black --check --diff --line-length 120 ./fabric
    pycodestyle --config=tox.ini fabric/
    # CI Check instance profile syntax
    /bin/bash ./scripts/service_lint.sh
    isort --check-only ./fabric ./scripts
    pytest ./fabric/tests --color=yes --ignore=examples --pythonwarnings=all --verbose {posargs:--cov=fabric --cov-report term-missing} --junitxml=build/audit_data/test_results.xml

source =
    fabric/libs
    .tox/*/lib/python*/site-packages/grubhub
