# $HOME/.config/alacritty/alacritty.toml
# by Douglas Jackson 2024-07-23

# Related Links
# Alacrity
# Themes: https://github.com/alacritty/alacritty-theme
# Specification: https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd
# TOML homepage: https://toml.io/en/v1.0.0
# Config locations: https://github.com/alacritty/alacritty/tree/master#configuration

import = [
    "~/.config/alacritty/themes/ubuntu.toml"
]

live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
decorations = "Full"
#decorations_theme_variant = "Light" # "Dark"
#opacity = 0.9
#blur = true
#option_as_alt = "Both"
padding = {x=5, y=5}
#dynamic_padding = false

[window.dimensions]
columns = 80
lines = 25

[font]
size = 16.0
normal = { family = "Monaco", style = "Regular" }
bold = { family = "Monaco", style = "Bold" }
italic = { family = "Monaco", style = "Italic" }
bold_italic = { family = "Monaco", style = "Bold Italic" }
