# linux settings

# Theme, font family and size
include          tango_dark-theme.conf
font_family      DejaVu Sans Mono
font_size        11.0

# Linux-specific copy/paste mappings
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard
