# linux settings

# Theme, font family and size
include          tango_dark-theme.conf
font_family      DejaVu Sans Mono
font_size        11.0

# Linux-specific copy/paste mappings
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard

# change font size for individual window
# Increase font size for the current OS window only
#map ctrl+shift+equal change_font_size current +2.0
#map ctrl+shift+plus  change_font_size current +2.0
# Decrease font size for the current OS window only
#map ctrl+shift+minus change_font_size current -2.0
# Reset font size back to default for the current OS window only
#map ctrl+shift+backspace change_font_size current 0
