# macOS settings

# Theme, font and font size
include                ubuntu-theme.conf
font_family            Monaco
font_size              16.0
font-thicken=false
bold-is-bright=false

# Configure the window title bar appearance
#hide_window_decorations titlebar-only
#macos_titlebar_color background

# Common macOS clipboard mapping overrides
map cmd+c copy_to_clipboard
map cmd+v paste_from_clipboard

# change font size for individual window
# Increase font size for the current OS window only
map cmd+equal            change_font_size current +2.0
map cmd+plus             change_font_size current +2.0
# Decrease font size for the current OS window only
map cmd+minus            change_font_size current -2.0
# Reset font size back to default for the current OS window only
map cmd+0                change_font_size current 0

# change font size for all windows
# Increase font size for the current OS window only
map cmd+shift+plus       change_font_size all +2.0
map cmd+shift+equal      change_font_size all +2.0
# Decrease font size for the current OS window only
map cmd+shift+minus      change_font_size all -2.0
# Reset font size back to default for the current OS window only
map cmd+shift+0          change_font_size all 0

# Go to specific tabs
# note: cmd+# goes to specific window
map cmd+1 goto_tab 1
map cmd+2 goto_tab 2
map cmd+3 goto_tab 3
map cmd+4 goto_tab 4
map cmd+5 goto_tab 5
map cmd+6 goto_tab 6
map cmd+7 goto_tab 7
map cmd+8 goto_tab 8
map cmd+9 goto_tab 9
map cmd+0 goto_tab 0
