# macOS settings

# Theme, font and font size
include                ubuntu-theme.conf
font_family            Monaco
font_size              16.0

# Configure the window title bar appearance
#hide_window_decorations titlebar-only
#macos_titlebar_color background

# Common macOS clipboard mapping overrides
map cmd+c copy_to_clipboard
map cmd+v paste_from_clipboard
